OR={
'Login':"xpath=//a[contains(text(),'Login')]",
'username':"xpath=//input[@id='ctl00_phBody_SignIn_txtEmail']",
'password':"xpath=//input[@id='ctl00_phBody_SignIn_txtPassword']",
'signin_button':"xpath=//input[@id='ctl00_phBody_SignIn_btnLogin']",
'Personal_setting':"xpath=//div[@class='ac-container']//li[1]//a[1]",
'Account_setting':"xpath=//input[@id='ctl00_phBody_AccountSetting_fvCustomer_imgUpdate']",
'First_name':"xpath=//input[@id='ctl00_phBody_AccountSetting_fvCustomer_txtFName']",
'Last_name':"xpath=//input[@id='ctl00_phBody_AccountSetting_fvCustomer_txtLName']",
'Edit':"xpath=//input[@id='ctl00_phBody_AccountSetting_fvCustomer_imgUpdate']",
'myadrss':"xpath=//ul[@class='ac-tabs']//a[contains(text(),'My Addresses')]",
'add_adress':"xpath=//input[@class='btn-red']",
'recipent_name':"xpath=//input[@id='ctl00_phBody_ShippingAddress_txtRecipientName']",
'cmpny_name':"xpath=//input[@id='ctl00_phBody_ShippingAddress_txtCompanyName']",
's_adress':"xpath=//textarea[@id='ctl00_phBody_ShippingAddress_txtAddress']",
'state':"xpath=//select[@id='ctl00_phBody_ShippingAddress_ddlState']",
's_state':"xpath=//option[contains(text(),'Karnataka')]",
'city':"xpath=//input[@id='ctl00_phBody_ShippingAddress_txtCity']",
'pincode':"xpath=//input[@id='ctl00_phBody_ShippingAddress_txtPincode']",
'phone':"xpath=//input[@id='ctl00_phBody_ShippingAddress_txtPhone']",
'submit':"xpath=//input[@id='ctl00_phBody_ShippingAddress_imgSubmit']",
'home_img':"xpath=//a[@class='sprite home-ico toplevel oneline']",
'child':"xpath=//div[@class='books-category']//a[contains(text(),'Children & Teens')]",
'Range':"xpath=//a[contains(text(),'Rs.500 - Rs.1000')]",
'relvance':"xpath=//select[@id='ddlSort']",
'search_result':"xpath=//div[@class='search-results fltrs demo3']//div[2]//div[4]//div[5]//a[2]//input[1]",
'search':"xpath=//input[@id='ctl00_TopSearch1_txtSearch']",
'wishlist':"xpath=//div[1]//div[4]//div[5]//a[2]//input[1]",
'f_authors':"xpath=//a[contains(text(),'Featured Authors')]",
'stphen':"xpath=//a[contains(text(),'Stephen King')]",
'add_wishlist':"xpath=//div[@class='search-results fltrs']//div[2]//div[4]//div[5]//a[2]//input[1]",
'Books':"xpath=//a[@class='toplevel top-drop hide-c']",
'show_all':"xpath=//a[contains(text(),'Show All Categories')]",
'true_stories':"xpath=//a[contains(text(),'True stories')]",
'grid_view':"xpath=//a[2]//img[1]",
'mouseover':"xpath=//div[1]//ul[1]//li[3]//div[1]//div[1]//a[1]//span[1]//img[1]",
'addwishlist':"xpath=//div[1]//ul[1]//li[3]//div[1]//div[2]//div[4]//span[2]//a[1]",
'remove':"xpath=//input[@id='ctl00_phBody_WishList_lvWishList_ctrl0_ImageButton1']"


}